version: "3.8"

services:
  api:
    build:
      context: ../../ # Point to the monorepo root
      dockerfile: apps/api/Dockerfile
    working_dir: /monorepo/apps/api
    volumes:
      - ../../:/monorepo # Mount the entire monorepo
      - /monorepo/node_modules
      - /monorepo/apps/api/node_modules
      - /monorepo/packages/shared/node_modules
    ports:
      - "3001:3001"
    command: pnpm start
