name: Deploy to Oracle Cloud VM
on:
  push:
    branches:
      - main
    paths:
      - "apps/api/**"
      - "packages/shared/**"
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VM_SSH_PRIVATE_KEY }}

      - name: Deploy to VM
        env:
          VM_IP: ${{ secrets.VM_IP }}
          VM_USER: ${{ secrets.VM_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $VM_USER@$VM_IP << EOF
            # Navigate to project directory
            cd /home/ubuntu/apps/TrckFnds/apps/api

            # Ensure using SSH remote
            git remote set-url origin git@github.com:justincanto/TrckFnds.git
            
            # Fetch latest changes and reset to main
            git fetch origin
            git reset --hard origin/main
            
            # Export environment variables
            export PORT=${{ secrets.PORT }}
            export AUTH_GOOGLE_ID=${{ secrets.AUTH_GOOGLE_ID }}
            export AUTH_GOOGLE_SECRET=${{ secrets.AUTH_GOOGLE_SECRET }}
            export DATABASE_URL=${{ secrets.DATABASE_URL }}
            export POWENS_BASE_URL=${{ secrets.POWENS_BASE_URL }}
            export POWENS_CLIENT_ID=${{ secrets.POWENS_CLIENT_ID }}
            export POWENS_CLIENT_SECRET=${{ secrets.POWENS_CLIENT_SECRET }}
            export INFURA_PROJECT_ID=${{ secrets.INFURA_PROJECT_ID }}
            export COIN_GECKO_API_KEY=${{ secrets.COIN_GECKO_API_KEY }}
            export FREE_CURRENCY_API_KEY=${{ secrets.FREE_CURRENCY_API_KEY }}
            export FRONT_URL=${{ secrets.FRONT_URL }}
            export API_BASE_URL=${{ secrets.API_BASE_URL }}
            export SESSION_SECRET=${{ secrets.SESSION_SECRET }}
            
            # Rebuild and restart containers
            docker compose down
            docker compose up --build -d
          EOF
